[package]
name = "ferrite-gui"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "The Ferrite desktop application."

[dependencies]
eframe = { version = "0.36.1", default-features = false, features = [
    "glow",
    "default_fonts",
    "accesskit",
] }
ferrite-core = { path = "../ferrite-core" }
